### ISSUE TITLE
Prevent upsertIf from expandingReferences if logical is undefined/false

### ISSUE THREAD

**Issue by lakhassane** [OpenFn/language-salesforce#35]
Currently we have this snippet in `upsertIf`
```js
const finalAttrs = expandReferences(attrs)(state);
  logical = expandReferences(logical)(state);

  if (logical) {
    console.log('logical', logical);
    console.info(
      `Upserting ${sObject} with externalId`,
      externalId,
      ':',
      finalAttrs
    );
  } else {
    co
```

The issue is that we expand references for `attrs` even if `logical` is false. Considering this if there is an issue in the fields (finalAttrs) the operation throws an error while it should ignore the execution with logical being false.

**Comment by taylordowns2000** [comment]
to document @lakhassane 's point here: logical is passed through `expandReferences(logical)(state)` so we don't need to _also_ expand refs for `attrs` unless logical is true. i'm in agreement with this. not a breaking change, as if the logical is `false` we won't create/upsert anyway.
